#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    positive=[]
    negative=[]
    zero=[]
    size=len(arr)
    for item in arr:
        if item>0:
            positive.append(item)
        elif item<0:
            negative.append(item)
        else:
            zero.append(item)
    p=len(positive)/size
    n=len(negative)/size
    z=len(zero)/size
    print(round(p,6))
    print(round(n,6))
    print(round(z,6))

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
